### ISSUE TITLE
Request for Permission and Guidance

### ISSUE THREAD

**Issue by Vansh479** [FiratUsta/Craptcha#1]
I saw this in the recent Laurie wired video, and I want to use it as my college project. But I am a student in my third year and knowledge-wise pretty cooked right now; I only know some basics and have never worked on a project myself. So I was wondering if I can connect with you on any platform you prefer and ask some questions only if you have some free time.

**Comment by FiratUsta** [comment]
You can do whatever you wish with this code within the limits of its license :)

For contacting me, you can email me at [ahmetfiratusta@gmail.com](mailto:ahmetfiratusta@gmail.com)
